/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.trade.update;

import java.util.concurrent.ConcurrentHashMap;

public class UpdateCancellationMicroservice {

	private static final ConcurrentHashMap<String, Double> walletBalances = new ConcurrentHashMap<>();
	private static final ConcurrentHashMap<String, Integer> shareQuantities = new ConcurrentHashMap();

	public String updateCancelTrade(Trade trade) {
		// Basic validation
		if (trade.getTradeId() == null) {
			return "Invalid trade details";
		}

		// Business logic for updating/cancelling existing trade
		Trade existingTrade = tradeStore.get(trade.getTradeId());
		if (existingTrade == null) {
			return "Trade not found";
		}

		// Additional logic for Buy or Sell
		if ("Buy".equalsIgnoreCase(existingTrade.getBuyOrSell())) {
			// Release blocked amount in wallet (mocking logic)
			// Assume wallet is a separate service or system
			System.out.println("Releasing blocked amount in wallet for " + existingTrade.getTraderId());
		} else if ("Sell".equalsIgnoreCase(existingTrade.getBuyOrSell())) {
			// Release blocked share quantity in broker system (mocking logic)
			System.out.println("Releasing blocked share quantity for " + existingTrade.getTraderId());
		}

		// Update the trade details and send messages to the Share Exchange (mocking
		// logic)
		sendToShareExchange(existingTrade);

		// Update this trade and make it available for end users to view (mocking logic)
		tradeStore.put(trade.getTradeId(), trade);

		return "Trade updated/cancelled successfully with ID: " + trade.getTradeId();
	}

	private void sendToShareExchange(Trade trade) {
		// Mocking logic for sending trade to Share Exchange
		System.out.println("Sending updated trade to Share Exchange: " + trade);
	}

	public static void main(String[] args) {
		UpdateCancellationMicroservice updateCancellationMicroservice = new UpdateCancellationMicroservice();

		// Example: Update Trade
		Trade updatedTrade = new Trade("ABC", 100, 60.0, "Trader123", "Buy", "T1");
		String updateResult = updateCancellationMicroservice.updateCancelTrade(updatedTrade);
		System.out.println(updateResult);

		// Example: Cancel Trade
		Trade cancelledTrade = new Trade("XYZ", 50, 80.0, "Trader456", "Sell", "T2");
		String cancelResult = updateCancellationMicroservice.updateCancelTrade(cancelledTrade);
		System.out.println(cancelResult);
	}
}
